# Generated by Django 5.2.8 on 2025-11-13 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название пункта')),
                ('named_url', models.CharField(blank=True, help_text='Имя named URL из urls.py (например: "home", "about")', max_length=100, verbose_name='Named URL')),
                ('explicit_url', models.CharField(blank=True, help_text='Явный URL (например: "/about/", "/contact/")', max_length=200, verbose_name='Явный URL')),
                ('menu_name', models.CharField(help_text='Уникальное название меню для template tag (например: "main_menu", "footer_menu")', max_length=50, verbose_name='Название меню')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='MainApp.menuitem', verbose_name='Родительский пункт')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['menu_name', 'order', 'name'],
            },
        ),
    ]
